name = "cf-workers-status-page"
compatibility_date = "2021-07-23"
workers_dev = true

[site]
bucket = "out"

[env.production]
kv_namespaces = [{binding="KV_STATUS_PAGE", id="8398f2e2d719453ab6d75e59e8d35aea"}]

[env.production.triggers]
crons = ["*/3 * * * *"]
