name = "cf-workers-status-page"
workers_dev = true
account_id = ""
type = "webpack"
webpack_config = "node_modules/flareact/webpack"
compatibility_date = "2021-07-23"

[triggers]
crons = ["*/3 * * * *"]

[site]
bucket = "out"
entry-point = "./"

[[kv_namespaces]]
binding = "KV_STATUS_PAGE"
id = "8398f2e2d719453ab6d75e59e8d35aea"
